#!/bin/bash

# Read the current dock orientation
orientation=$(defaults read com.apple.dock orientation)

# Check the current orientation and toggle it between left and right
if [[ "$orientation" == "left" ]]; then
  defaults write com.apple.dock orientation right && killall Dock
  echo "Dock orientation set to right"
elif [[ "$orientation" == "right" ]]; then
  defaults write com.apple.dock orientation left && killall Dock
  echo "Dock orientation set to left"
else
  echo "Unknown dock orientation: $orientation"
  exit 1
fi

